// [agentyx-provenance v1] generated by cobol_cics_to_springreact (grounded golden)
package com.carddemo;

import com.carddemo.domain.*;
import com.carddemo.repo.*;
import com.carddemo.service.*;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import java.math.BigDecimal;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Oracle-grounded goldens — expected values are computed by executing the
 * source COBOL (COBIL00C bill-pay, CBACT04C interest) through the agentyx
 * COBOL interpreter at emit time, NOT copied from the Java. Each goes RED if
 * the service diverges from the COBOL rule.
 */
@SpringBootTest(classes = CardDemoApplication.class)
class CardDemoGroundedGoldenTest {

    @Autowired BillPayService billPay;
    @Autowired InterestService interestSvc;
    @Autowired AccountRepository accounts;
    @Autowired TranCatBalRepository tranCatBals;
    @Autowired DisGroupRepository disGroups;

    @Test
    void billPay_paysFullBalance_grounded() {
        Account a = new Account();
        a.setAcctId(900000001L);
        a.setAcctActiveStatus("Y");
        a.setAcctCurrBal(new BigDecimal("1250.75"));
        accounts.save(a);

        Map<String,Object> r = billPay.pay(900000001L);

        // GROUNDED (COBIL00C PROCESS-ENTER-KEY):
        assertEquals(0,
            new BigDecimal("1250.75").compareTo((BigDecimal) r.get("paymentAmount")),
            "payment must equal the full balance (COBIL00C)");
        assertEquals(0,
            new BigDecimal("0.0").compareTo((BigDecimal) r.get("newBalance")),
            "balance must be zeroed after full payment (COBIL00C)");
    }

    @Test
    void interestCalc_accruesMonthly_grounded() {
        Account a = new Account();
        a.setAcctId(900000002L);
        a.setAcctActiveStatus("Y");
        a.setAcctGroupId("DEFG");
        a.setAcctCurrBal(new BigDecimal("0.00"));
        accounts.save(a);

        TranCatBal cb = new TranCatBal();
        cb.setTrancatAcctId(900000002L);
        cb.setTrancatTypeCd("01");
        cb.setTrancatCd(1L);
        cb.setTranCatBal(new BigDecimal("1000.00"));
        tranCatBals.save(cb);

        DisGroup dg = new DisGroup();
        dg.setDisAcctGroupId("DEFG");
        dg.setDisTranTypeCd("01");
        dg.setDisTranCatCd(1L);
        dg.setDisIntRate(new BigDecimal("12.00"));
        disGroups.save(dg);

        interestSvc.runInterestCalc();

        Account after = accounts.findById(900000002L).orElseThrow();
        // GROUNDED (CBACT04C 1300-COMPUTE-INTEREST: catBal * rate / 1200):
        assertEquals(0,
            new BigDecimal("10.0").compareTo(after.getAcctCurrBal()),
            "monthly interest = catBal * rate / 1200, accrued to balance (CBACT04C)");
    }
}
