// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
@SpringBootApplication public class CardDemoApplication {
    public static void main(String[] a){ SpringApplication.run(CardDemoApplication.class, a); }
}
