// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.repo;

import com.carddemo.domain.CardXref;
import org.springframework.data.jpa.repository.JpaRepository;

public interface CardXrefRepository extends JpaRepository<CardXref, String> {
    java.util.List<CardXref> findByXrefAcctId(Long xrefAcctId);
    java.util.List<CardXref> findByXrefCustId(Long xrefCustId);
}
