// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.repo;

import com.carddemo.domain.Dalytran;
import org.springframework.data.jpa.repository.JpaRepository;

public interface DalytranRepository extends JpaRepository<Dalytran, Long> {

}
