// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.repo;

import com.carddemo.domain.DisGroup;
import org.springframework.data.jpa.repository.JpaRepository;

public interface DisGroupRepository extends JpaRepository<DisGroup, Long> {
    java.util.Optional<DisGroup> findByDisAcctGroupIdAndDisTranTypeCdAndDisTranCatCd(String disAcctGroupId, String disTranTypeCd, Long disTranCatCd);
}
