// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.repo;

import com.carddemo.domain.Tran;
import org.springframework.data.jpa.repository.JpaRepository;

public interface TranRepository extends JpaRepository<Tran, String> {
    java.util.List<Tran> findByTranCardNum(String tranCardNum);
    java.util.Optional<Tran> findTopByOrderByTranIdDesc();
}
