// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.repo;

import com.carddemo.domain.TranCatBal;
import org.springframework.data.jpa.repository.JpaRepository;

public interface TranCatBalRepository extends JpaRepository<TranCatBal, Long> {
    java.util.List<TranCatBal> findByTrancatAcctId(Long trancatAcctId);
    java.util.Optional<TranCatBal> findByTrancatAcctIdAndTrancatTypeCdAndTrancatCd(Long trancatAcctId, String trancatTypeCd, Long trancatCd);
}
