// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.batch;

import org.springframework.batch.core.*;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.annotation.*;
import org.springframework.transaction.PlatformTransactionManager;

@Configuration
public class CARDFILEBatchConfig {
    // Source JCL: CARDFILE.jcl (steps: SDSF -> IDCAMS -> IDCAMS -> IDCAMS -> IDCAMS -> IDCAMS -> IDCAMS -> SDSF)
    @Bean Job cardfileJob(JobRepository jr, PlatformTransactionManager tx) {
        Step s = new StepBuilder("CARDFILE-step", jr)
            .tasklet((c, ctx) -> RepeatStatus.FINISHED, tx).build();
        return new JobBuilder("CARDFILE", jr).start(s).build();
    }
}
