// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.batch;

import com.carddemo.service.StatementService;
import org.springframework.batch.core.*;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.annotation.*;
import org.springframework.transaction.PlatformTransactionManager;

@Configuration
public class CREASTMTBatchConfig {
    // Source JCL: CREASTMT.JCL — reimplemented via StatementService.generate()
    @Bean Job creastmtJob(JobRepository jr, PlatformTransactionManager tx, StatementService svc) {
        Step s = new StepBuilder("CREASTMT-step", jr)
            .tasklet((c, ctx) -> { svc.generate(); return RepeatStatus.FINISHED; }, tx).build();
        return new JobBuilder("CREASTMT", jr).start(s).build();
    }
}
