// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.batch;

import org.springframework.batch.core.*;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.annotation.*;
import org.springframework.transaction.PlatformTransactionManager;

@Configuration
public class CUSTFILEBatchConfig {
    // Source JCL: CUSTFILE.jcl (steps: SDSF -> IDCAMS -> IDCAMS -> IDCAMS -> SDSF)
    @Bean Job custfileJob(JobRepository jr, PlatformTransactionManager tx) {
        Step s = new StepBuilder("CUSTFILE-step", jr)
            .tasklet((c, ctx) -> RepeatStatus.FINISHED, tx).build();
        return new JobBuilder("CUSTFILE", jr).start(s).build();
    }
}
