// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.batch;

import com.carddemo.service.InterestService;
import org.springframework.batch.core.*;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.annotation.*;
import org.springframework.transaction.PlatformTransactionManager;

@Configuration
public class INTCALCBatchConfig {
    // Source JCL: INTCALC.jcl — reimplemented via InterestService.runInterestCalc()
    @Bean Job intcalcJob(JobRepository jr, PlatformTransactionManager tx, InterestService svc) {
        Step s = new StepBuilder("INTCALC-step", jr)
            .tasklet((c, ctx) -> { svc.runInterestCalc(); return RepeatStatus.FINISHED; }, tx).build();
        return new JobBuilder("INTCALC", jr).start(s).build();
    }
}
