// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.batch;

import com.carddemo.service.DailyPostingService;
import org.springframework.batch.core.*;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.annotation.*;
import org.springframework.transaction.PlatformTransactionManager;

@Configuration
public class POSTTRANBatchConfig {
    // Source JCL: POSTTRAN.jcl — reimplemented via DailyPostingService.postDaily()
    @Bean Job posttranJob(JobRepository jr, PlatformTransactionManager tx, DailyPostingService svc) {
        Step s = new StepBuilder("POSTTRAN-step", jr)
            .tasklet((c, ctx) -> { svc.postDaily(); return RepeatStatus.FINISHED; }, tx).build();
        return new JobBuilder("POSTTRAN", jr).start(s).build();
    }
}
