// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.batch;

import com.carddemo.repo.CardXrefRepository;
import org.springframework.batch.core.*;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.annotation.*;
import org.springframework.transaction.PlatformTransactionManager;

@Configuration
public class READXREFBatchConfig {
    // Source JCL: READXREF.jcl — sequential file read reimplemented over CardXrefRepository
    @Bean Job readxrefJob(JobRepository jr, PlatformTransactionManager tx, CardXrefRepository repo) {
        Step s = new StepBuilder("READXREF-step", jr)
            .tasklet((c, ctx) -> { repo.findAll().size(); return RepeatStatus.FINISHED; }, tx).build();
        return new JobBuilder("READXREF", jr).start(s).build();
    }
}
