// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.batch;

import com.carddemo.repo.CardRepository;
import org.springframework.batch.core.*;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.annotation.*;
import org.springframework.transaction.PlatformTransactionManager;

@Configuration
public class READCARDBatchConfig {
    // Source JCL: READCARD.jcl — sequential file read reimplemented over CardRepository
    @Bean Job readcardJob(JobRepository jr, PlatformTransactionManager tx, CardRepository repo) {
        Step s = new StepBuilder("READCARD-step", jr)
            .tasklet((c, ctx) -> { repo.findAll().size(); return RepeatStatus.FINISHED; }, tx).build();
        return new JobBuilder("READCARD", jr).start(s).build();
    }
}
