// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.batch;

import com.carddemo.repo.AccountRepository;
import org.springframework.batch.core.*;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.annotation.*;
import org.springframework.transaction.PlatformTransactionManager;

@Configuration
public class READACCTBatchConfig {
    // Source JCL: READACCT.jcl — sequential file read reimplemented over AccountRepository
    @Bean Job readacctJob(JobRepository jr, PlatformTransactionManager tx, AccountRepository repo) {
        Step s = new StepBuilder("READACCT-step", jr)
            .tasklet((c, ctx) -> { repo.findAll().size(); return RepeatStatus.FINISHED; }, tx).build();
        return new JobBuilder("READACCT", jr).start(s).build();
    }
}
