// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.batch;

import org.springframework.batch.core.*;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.annotation.*;
import org.springframework.transaction.PlatformTransactionManager;

@Configuration
public class TRANCATGBatchConfig {
    // Source JCL: TRANCATG.jcl (steps: IDCAMS -> IDCAMS -> IDCAMS)
    @Bean Job trancatgJob(JobRepository jr, PlatformTransactionManager tx) {
        Step s = new StepBuilder("TRANCATG-step", jr)
            .tasklet((c, ctx) -> RepeatStatus.FINISHED, tx).build();
        return new JobBuilder("TRANCATG", jr).start(s).build();
    }
}
