// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.domain;

import jakarta.persistence.*;
import lombok.Getter; import lombok.Setter; import lombok.NoArgsConstructor;

@Entity
@Table(name = "account")
@Getter @Setter @NoArgsConstructor
public class Account {
    @Id
    @Column(name = "acct_id")
    private Long acctId;
    @Column(name = "acct_active_status")
    private String acctActiveStatus;
    @Column(name = "acct_curr_bal")
    private java.math.BigDecimal acctCurrBal;
    @Column(name = "acct_credit_limit")
    private java.math.BigDecimal acctCreditLimit;
    @Column(name = "acct_cash_credit_limit")
    private java.math.BigDecimal acctCashCreditLimit;
    @Column(name = "acct_open_date")
    private String acctOpenDate;
    @Column(name = "acct_expiraion_date")
    private String acctExpiraionDate;
    @Column(name = "acct_reissue_date")
    private String acctReissueDate;
    @Column(name = "acct_curr_cyc_credit")
    private java.math.BigDecimal acctCurrCycCredit;
    @Column(name = "acct_curr_cyc_debit")
    private java.math.BigDecimal acctCurrCycDebit;
    @Column(name = "acct_addr_zip")
    private String acctAddrZip;
    @Column(name = "acct_group_id")
    private String acctGroupId;
}
