// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.domain;

import jakarta.persistence.*;
import lombok.Getter; import lombok.Setter; import lombok.NoArgsConstructor;

@Entity
@Table(name = "card")
@Getter @Setter @NoArgsConstructor
public class Card {
    @Id
    @Column(name = "card_num")
    private String cardNum;
    @Column(name = "card_acct_id")
    private Long cardAcctId;
    @Column(name = "card_cvv_cd")
    private Long cardCvvCd;
    @Column(name = "card_embossed_name")
    private String cardEmbossedName;
    @Column(name = "card_expiraion_date")
    private String cardExpiraionDate;
    @Column(name = "card_active_status")
    private String cardActiveStatus;
}
