// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.domain;

import jakarta.persistence.*;
import lombok.Getter; import lombok.Setter; import lombok.NoArgsConstructor;

@Entity
@Table(name = "card_xref")
@Getter @Setter @NoArgsConstructor
public class CardXref {
    @Id
    @Column(name = "xref_card_num")
    private String xrefCardNum;
    @Column(name = "xref_cust_id")
    private Long xrefCustId;
    @Column(name = "xref_acct_id")
    private Long xrefAcctId;
}
