// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.domain;

import jakarta.persistence.*;
import lombok.Getter; import lombok.Setter; import lombok.NoArgsConstructor;

@Entity
@Table(name = "dalytran")
@Getter @Setter @NoArgsConstructor
public class Dalytran {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "dalytran_id")
    private String dalytranId;
    @Column(name = "dalytran_type_cd")
    private String dalytranTypeCd;
    @Column(name = "dalytran_cat_cd")
    private Long dalytranCatCd;
    @Column(name = "dalytran_source")
    private String dalytranSource;
    @Column(name = "dalytran_desc")
    private String dalytranDesc;
    @Column(name = "dalytran_amt")
    private java.math.BigDecimal dalytranAmt;
    @Column(name = "dalytran_merchant_id")
    private Long dalytranMerchantId;
    @Column(name = "dalytran_merchant_name")
    private String dalytranMerchantName;
    @Column(name = "dalytran_merchant_city")
    private String dalytranMerchantCity;
    @Column(name = "dalytran_merchant_zip")
    private String dalytranMerchantZip;
    @Column(name = "dalytran_card_num")
    private String dalytranCardNum;
    @Column(name = "dalytran_orig_ts")
    private String dalytranOrigTs;
    @Column(name = "dalytran_proc_ts")
    private String dalytranProcTs;
}
