// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.domain;

import jakarta.persistence.*;
import lombok.Getter; import lombok.Setter; import lombok.NoArgsConstructor;

@Entity
@Table(name = "dis_group")
@Getter @Setter @NoArgsConstructor
public class DisGroup {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "dis_acct_group_id")
    private String disAcctGroupId;
    @Column(name = "dis_tran_type_cd")
    private String disTranTypeCd;
    @Column(name = "dis_tran_cat_cd")
    private Long disTranCatCd;
    @Column(name = "dis_int_rate")
    private java.math.BigDecimal disIntRate;
}
