// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.domain;

import jakarta.persistence.*;
import lombok.Getter; import lombok.Setter; import lombok.NoArgsConstructor;

@Entity
@Table(name = "security_user")
@Getter @Setter @NoArgsConstructor
public class SecurityUser {
    @Id
    @Column(name = "sec_usr_id")
    private String secUsrId;
    @Column(name = "sec_usr_fname")
    private String secUsrFname;
    @Column(name = "sec_usr_lname")
    private String secUsrLname;
    @Column(name = "sec_usr_pwd")
    private String secUsrPwd;
    @Column(name = "sec_usr_type")
    private String secUsrType;
    @Column(name = "sec_usr_filler")
    private String secUsrFiller;
}
