// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.domain;

import jakarta.persistence.*;
import lombok.Getter; import lombok.Setter; import lombok.NoArgsConstructor;

@Entity
@Table(name = "tran_cat_bal")
@Getter @Setter @NoArgsConstructor
public class TranCatBal {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "trancat_acct_id")
    private Long trancatAcctId;
    @Column(name = "trancat_type_cd")
    private String trancatTypeCd;
    @Column(name = "trancat_cd")
    private Long trancatCd;
    @Column(name = "tran_cat_bal")
    private java.math.BigDecimal tranCatBal;
}
