// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.domain;

import jakarta.persistence.*;
import lombok.Getter; import lombok.Setter; import lombok.NoArgsConstructor;

@Entity
@Table(name = "tran")
@Getter @Setter @NoArgsConstructor
public class Tran {
    @Id
    @Column(name = "tran_id")
    private String tranId;
    @Column(name = "tran_type_cd")
    private String tranTypeCd;
    @Column(name = "tran_cat_cd")
    private Long tranCatCd;
    @Column(name = "tran_source")
    private String tranSource;
    @Column(name = "tran_desc")
    private String tranDesc;
    @Column(name = "tran_amt")
    private java.math.BigDecimal tranAmt;
    @Column(name = "tran_merchant_id")
    private Long tranMerchantId;
    @Column(name = "tran_merchant_name")
    private String tranMerchantName;
    @Column(name = "tran_merchant_city")
    private String tranMerchantCity;
    @Column(name = "tran_merchant_zip")
    private String tranMerchantZip;
    @Column(name = "tran_card_num")
    private String tranCardNum;
    @Column(name = "tran_orig_ts")
    private String tranOrigTs;
    @Column(name = "tran_proc_ts")
    private String tranProcTs;
}
