// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.domain;

import jakarta.persistence.*;
import lombok.Getter; import lombok.Setter; import lombok.NoArgsConstructor;

@Entity
@Table(name = "tran_type")
@Getter @Setter @NoArgsConstructor
public class TranType {
    @Id
    @Column(name = "tran_type")
    private String tranType;
    @Column(name = "tran_type_desc")
    private String tranTypeDesc;
}
