// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.*;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.DatabasePopulatorUtils;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;
import javax.sql.DataSource;
@Configuration public class DataLoader {
    @Bean CommandLineRunner seedReferenceData(JdbcTemplate jdbc, DataSource ds) {
        return args -> {
            Integer n = jdbc.queryForObject("SELECT COUNT(*) FROM account", Integer.class);
            if (n != null && n > 0) return;
            ResourceDatabasePopulator p = new ResourceDatabasePopulator(
                new ClassPathResource("db/seed/data.sql"));
            p.setSeparator(";");
            DatabasePopulatorUtils.execute(p, ds);
        };
    }
}
