// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.config;

import com.carddemo.domain.SecurityUser; import com.carddemo.repo.SecurityUserRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.*;
@Configuration @Profile("dev")
public class DataSeeder {
    @Bean CommandLineRunner seed(SecurityUserRepository users) { return args -> {
        if (users.count() == 0) {
            SecurityUser a = new SecurityUser(); a.setSecUsrId("ADMIN001"); a.setSecUsrPwd("PASSWORD"); a.setSecUsrType("A");
            SecurityUser u = new SecurityUser(); u.setSecUsrId("USER0001"); u.setSecUsrPwd("PASSWORD"); u.setSecUsrType("U");
            users.save(a); users.save(u);
        } }; }
}
