// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.util;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
/** Date validation — reimplements CSUTLDTC (CEEDAYS): a date string is
 *  valid iff it parses as an ISO yyyy-MM-dd calendar date. */
public final class DateValidator {
    private DateValidator() {}
    private static final DateTimeFormatter ISO = DateTimeFormatter.ISO_LOCAL_DATE;
    public static boolean isValid(String date) {
        if (date == null) return false;
        try { LocalDate.parse(date.trim(), ISO); return true; }
        catch (Exception e) { return false; }
    }
}
