// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.Card; import com.carddemo.repo.CardRepository;
import org.springframework.web.bind.annotation.*;
import java.util.List;
/** Card list for an account — reimplements COCRDLIC (account-scoped
 *  card browse), not a global list-all. */
@RestController @RequestMapping("/api/accounts")
public class AccountCardsController {
    private final CardRepository cards;
    public AccountCardsController(CardRepository c){ this.cards=c; }
    @GetMapping("/{acctId}/cards") public List<Card> cards(@PathVariable Long acctId){
        return cards.findByCardAcctId(acctId);
    }
}
