// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.Account;
import com.carddemo.repo.AccountRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/accounts")
public class AccountController {
    private final AccountRepository repo;
    public AccountController(AccountRepository repo) { this.repo = repo; }

    @GetMapping public List<Account> list() { return repo.findAll(); }
    @GetMapping("/{id}") public ResponseEntity<Account> get(@PathVariable Long id) {
        return repo.findById(id).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build()); }
    @PostMapping public Account create(@RequestBody Account body) { return repo.save(body); }
    @PutMapping("/{id}") public Account update(@PathVariable Long id, @RequestBody Account body) { return repo.save(body); }
    @DeleteMapping("/{id}") public void delete(@PathVariable Long id) { repo.deleteById(id); }
}
