// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.service.AccountViewService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.Map;
@RestController @RequestMapping("/api/accounts")
public class AccountViewController {
    private final AccountViewService svc;
    public AccountViewController(AccountViewService s){ this.svc=s; }
    @GetMapping("/{acctId}/view") public ResponseEntity<?> view(@PathVariable Long acctId){
        try { return ResponseEntity.ok(svc.view(acctId)); }
        catch (IllegalArgumentException e){ return ResponseEntity.status(404).body(Map.of("error",e.getMessage())); }
    }
}
