// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.service.AccountUpdateService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.Map;
@RestController @RequestMapping("/api/accounts")
public class AccountUpdateController {
    private final AccountUpdateService svc;
    public AccountUpdateController(AccountUpdateService s){ this.svc=s; }
    @PutMapping("/{acctId}/update") public ResponseEntity<?> update(@PathVariable Long acctId, @RequestBody Map<String,Object> body){
        try { return ResponseEntity.ok(svc.update(acctId, body)); }
        catch (IllegalArgumentException e){
            String m = e.getMessage()==null?"":e.getMessage();
            int code = m.contains("NOT found") ? 404 : 400;
            return ResponseEntity.status(code).body(Map.of("error", m)); }
    }
}
