// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.SecurityUser; import com.carddemo.repo.SecurityUserRepository;
import com.carddemo.security.JwtService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.Map;
@RestController @RequestMapping("/api/auth")
public class AuthController {
    private final SecurityUserRepository users; private final JwtService jwt;
    public AuthController(SecurityUserRepository u, JwtService j){ this.users=u; this.jwt=j; }
    @PostMapping("/signon")
    public ResponseEntity<?> signon(@RequestBody Map<String,String> body) {
        String id = body.getOrDefault("userId","").trim();
        String pw = body.getOrDefault("password","");
        var u = users.findById(id).orElse(null);
        if (u == null || !pw.equals(u.getSecUsrPwd()==null?"":u.getSecUsrPwd().trim()))
            return ResponseEntity.status(401).body(Map.of("error","Invalid credentials"));
        String role = "A".equalsIgnoreCase(u.getSecUsrType()==null?"":u.getSecUsrType().trim()) ? "ADMIN" : "USER";
        return ResponseEntity.ok(Map.of("token", jwt.issue(id, role), "role", role, "userId", id));
    }
}
