// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.service.BillPayService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.Map;
@RestController @RequestMapping("/api/billpay")
public class BillPayController {
    private final BillPayService svc;
    public BillPayController(BillPayService s){ this.svc=s; }
    @PostMapping("/{acctId}") public ResponseEntity<?> pay(@PathVariable Long acctId){
        try { return ResponseEntity.ok(svc.pay(acctId)); }
        catch (IllegalArgumentException e){ return ResponseEntity.status(404).body(Map.of("error",e.getMessage())); }
        catch (IllegalStateException e){ return ResponseEntity.badRequest().body(Map.of("error",e.getMessage())); }
    }
}
