// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.Card;
import com.carddemo.repo.CardRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/cards")
public class CardController {
    private final CardRepository repo;
    public CardController(CardRepository repo) { this.repo = repo; }

    @GetMapping public List<Card> list() { return repo.findAll(); }
    @GetMapping("/{id}") public ResponseEntity<Card> get(@PathVariable String id) {
        return repo.findById(id).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build()); }
    @PostMapping public Card create(@RequestBody Card body) { return repo.save(body); }
    @PutMapping("/{id}") public Card update(@PathVariable String id, @RequestBody Card body) { return repo.save(body); }
    @DeleteMapping("/{id}") public void delete(@PathVariable String id) { repo.deleteById(id); }
}
