// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.Card; import com.carddemo.service.CardUpdateService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.Map;
@RestController @RequestMapping("/api/cards")
public class CardUpdateController {
    private final CardUpdateService svc;
    public CardUpdateController(CardUpdateService s){ this.svc=s; }
    @PutMapping("/{cardNum}/update") public ResponseEntity<?> update(@PathVariable String cardNum, @RequestBody Card body){
        try { return ResponseEntity.ok(svc.update(cardNum, body)); }
        catch (IllegalArgumentException e){ return ResponseEntity.status(404).body(Map.of("error",e.getMessage())); }
    }
}
