// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.Tran; import com.carddemo.repo.TranRepository;
import org.springframework.web.bind.annotation.*;
import java.util.List;
/** Transaction list for a card — reimplements COTRN00C (card-scoped
 *  transaction history), not a global list-all. */
@RestController @RequestMapping("/api/cards")
public class CardTransactionsController {
    private final TranRepository trans;
    public CardTransactionsController(TranRepository t){ this.trans=t; }
    @GetMapping("/{cardNum}/transactions") public List<Tran> txns(@PathVariable String cardNum){
        return trans.findByTranCardNum(cardNum);
    }
}
