// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.CardXref;
import com.carddemo.repo.CardXrefRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/card-xrefs")
public class CardXrefController {
    private final CardXrefRepository repo;
    public CardXrefController(CardXrefRepository repo) { this.repo = repo; }

    @GetMapping public List<CardXref> list() { return repo.findAll(); }
    @GetMapping("/{id}") public ResponseEntity<CardXref> get(@PathVariable String id) {
        return repo.findById(id).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build()); }
    @PostMapping public CardXref create(@RequestBody CardXref body) { return repo.save(body); }
    @PutMapping("/{id}") public CardXref update(@PathVariable String id, @RequestBody CardXref body) { return repo.save(body); }
    @DeleteMapping("/{id}") public void delete(@PathVariable String id) { repo.deleteById(id); }
}
