// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.DisGroup;
import com.carddemo.repo.DisGroupRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/dis-groups")
public class DisGroupController {
    private final DisGroupRepository repo;
    public DisGroupController(DisGroupRepository repo) { this.repo = repo; }

    @GetMapping public List<DisGroup> list() { return repo.findAll(); }
    @GetMapping("/{id}") public ResponseEntity<DisGroup> get(@PathVariable Long id) {
        return repo.findById(id).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build()); }
    @PostMapping public DisGroup create(@RequestBody DisGroup body) { return repo.save(body); }
    @PutMapping("/{id}") public DisGroup update(@PathVariable Long id, @RequestBody DisGroup body) { return repo.save(body); }
    @DeleteMapping("/{id}") public void delete(@PathVariable Long id) { repo.deleteById(id); }
}
