// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.service.PostingService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal; import java.util.Map;
@RestController @RequestMapping("/api/posting")
public class PostingController {
    private final PostingService svc;
    public PostingController(PostingService s){ this.svc=s; }
    @PostMapping public ResponseEntity<?> post(@RequestBody Map<String,Object> b){
        try {
            Long acctId = Long.valueOf(String.valueOf(b.get("acctId")));
            String typeCd = b.get("typeCd")==null?null:String.valueOf(b.get("typeCd"));
            Long catCd = b.get("catCd")==null?null:Long.valueOf(String.valueOf(b.get("catCd")));
            BigDecimal amt = new BigDecimal(String.valueOf(b.get("amt")));
            return ResponseEntity.ok(svc.post(acctId, typeCd, catCd, amt));
        } catch (IllegalArgumentException e){ return ResponseEntity.badRequest().body(Map.of("error",e.getMessage())); }
        catch (IllegalStateException e){ return ResponseEntity.status(422).body(Map.of("error",e.getMessage())); }
    }
}
