// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import java.util.Map;
@RestController public class RootController {
    @GetMapping("/")
    public Map<String,Object> root(){ return Map.of("app","carddemo","status","ok"); }
}
