// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.SecurityUser;
import com.carddemo.repo.SecurityUserRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/security-users")
public class SecurityUserController {
    private final SecurityUserRepository repo;
    public SecurityUserController(SecurityUserRepository repo) { this.repo = repo; }

    @GetMapping public List<SecurityUser> list() { return repo.findAll(); }
    @GetMapping("/{id}") public ResponseEntity<SecurityUser> get(@PathVariable String id) {
        return repo.findById(id).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build()); }
    @PostMapping public SecurityUser create(@RequestBody SecurityUser body) { return repo.save(body); }
    @PutMapping("/{id}") public SecurityUser update(@PathVariable String id, @RequestBody SecurityUser body) { return repo.save(body); }
    @DeleteMapping("/{id}") public void delete(@PathVariable String id) { repo.deleteById(id); }
}
