// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.TranType;
import com.carddemo.repo.TranTypeRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/tran-types")
public class TranTypeController {
    private final TranTypeRepository repo;
    public TranTypeController(TranTypeRepository repo) { this.repo = repo; }

    @GetMapping public List<TranType> list() { return repo.findAll(); }
    @GetMapping("/{id}") public ResponseEntity<TranType> get(@PathVariable String id) {
        return repo.findById(id).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build()); }
    @PostMapping public TranType create(@RequestBody TranType body) { return repo.save(body); }
    @PutMapping("/{id}") public TranType update(@PathVariable String id, @RequestBody TranType body) { return repo.save(body); }
    @DeleteMapping("/{id}") public void delete(@PathVariable String id) { repo.deleteById(id); }
}
