// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.Tran; import com.carddemo.service.TransactionService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.Map;
@RestController @RequestMapping("/api/transactions")
public class TransactionAddController {
    private final TransactionService svc;
    public TransactionAddController(TransactionService s){ this.svc=s; }
    @PostMapping("/add") public ResponseEntity<?> add(@RequestBody Tran body){
        try { return ResponseEntity.ok(svc.add(body)); }
        catch (IllegalArgumentException e){ return ResponseEntity.badRequest().body(Map.of("error",e.getMessage())); }
    }
}
