// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.TranCatBal;
import com.carddemo.repo.TranCatBalRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/tran-cat-bals")
public class TranCatBalController {
    private final TranCatBalRepository repo;
    public TranCatBalController(TranCatBalRepository repo) { this.repo = repo; }

    @GetMapping public List<TranCatBal> list() { return repo.findAll(); }
    @GetMapping("/{id}") public ResponseEntity<TranCatBal> get(@PathVariable Long id) {
        return repo.findById(id).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build()); }
    @PostMapping public TranCatBal create(@RequestBody TranCatBal body) { return repo.save(body); }
    @PutMapping("/{id}") public TranCatBal update(@PathVariable Long id, @RequestBody TranCatBal body) { return repo.save(body); }
    @DeleteMapping("/{id}") public void delete(@PathVariable Long id) { repo.deleteById(id); }
}
