// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.web;

import com.carddemo.domain.Tran;
import com.carddemo.repo.TranRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/trans")
public class TranController {
    private final TranRepository repo;
    public TranController(TranRepository repo) { this.repo = repo; }

    @GetMapping public List<Tran> list() { return repo.findAll(); }
    @GetMapping("/{id}") public ResponseEntity<Tran> get(@PathVariable String id) {
        return repo.findById(id).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build()); }
    @PostMapping public Tran create(@RequestBody Tran body) { return repo.save(body); }
    @PutMapping("/{id}") public Tran update(@PathVariable String id, @RequestBody Tran body) { return repo.save(body); }
    @DeleteMapping("/{id}") public void delete(@PathVariable String id) { repo.deleteById(id); }
}
