// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.security;

import io.jsonwebtoken.*; import io.jsonwebtoken.security.Keys;
import org.springframework.stereotype.Service;
import javax.crypto.SecretKey; import java.util.Date;
@Service public class JwtService {
    private final SecretKey key = Keys.hmacShaKeyFor("carddemo-dev-secret-key-change-me-please-1234567890".getBytes());
    public String issue(String user, String role) {
        return Jwts.builder().subject(user).claim("role", role)
            .issuedAt(new Date()).expiration(new Date(System.currentTimeMillis()+86400000))
            .signWith(key).compact(); }
    public Jws<Claims> parse(String token) { return Jwts.parser().verifyWith(key).build().parseSignedClaims(token); }
}
