// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.service;

import com.carddemo.domain.Account; import com.carddemo.repo.AccountRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.util.*; import java.util.function.Consumer;
import java.util.regex.Pattern;
/** Account update — reimplements COACTUPC validation: numeric limits/
 *  balances (NUMVAL-C), YYYY-MM-DD dates, and '*' = preserve existing.
 *  Only the documented editable account fields are updatable. */
@Service public class AccountUpdateService {
    private final AccountRepository accounts;
    private static final Pattern DATE = Pattern.compile("\\d{4}-\\d{2}-\\d{2}");
    public AccountUpdateService(AccountRepository a){ this.accounts=a; }
    private static void applyDecimal(Consumer<BigDecimal> set, Object raw, String name){
        if (raw==null) return; String s=String.valueOf(raw).trim();
        if (s.isEmpty()||s.equals("*")) return;
        try { set.accept(new BigDecimal(s)); }
        catch (NumberFormatException e){ throw new IllegalArgumentException(name+" must be numeric"); } }
    private static void applyDate(Consumer<String> set, Object raw, String name){
        if (raw==null) return; String s=String.valueOf(raw).trim();
        if (s.isEmpty()||s.equals("*")) return;
        if (!DATE.matcher(s).matches()) throw new IllegalArgumentException(name+" must be YYYY-MM-DD");
        set.accept(s); }
    private static void applyText(Consumer<String> set, Object raw){
        if (raw==null) return; String s=String.valueOf(raw); if (s.equals("*")) return; set.accept(s); }
    @Transactional public Account update(Long acctId, Map<String,Object> body){
        Account acc = accounts.findById(acctId).orElseThrow(
            () -> new IllegalArgumentException("Account ID NOT found"));
        applyDecimal(acc::setAcctCreditLimit, body.get("acctCreditLimit"), "acctCreditLimit");
        applyDecimal(acc::setAcctCashCreditLimit, body.get("acctCashCreditLimit"), "acctCashCreditLimit");
        applyDecimal(acc::setAcctCurrBal, body.get("acctCurrBal"), "acctCurrBal");
        applyDecimal(acc::setAcctCurrCycCredit, body.get("acctCurrCycCredit"), "acctCurrCycCredit");
        applyDecimal(acc::setAcctCurrCycDebit, body.get("acctCurrCycDebit"), "acctCurrCycDebit");
        applyText(acc::setAcctGroupId, body.get("acctGroupId"));
        applyDate(acc::setAcctOpenDate, body.get("acctOpenDate"), "acctOpenDate");
        applyDate(acc::setAcctExpiraionDate, body.get("acctExpiraionDate"), "acctExpiraionDate");
        applyDate(acc::setAcctReissueDate, body.get("acctReissueDate"), "acctReissueDate");
        applyText(acc::setAcctActiveStatus, body.get("acctActiveStatus"));
        return accounts.save(acc);
    }
}
