// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.service;

import com.carddemo.domain.*; import com.carddemo.repo.*;
import org.springframework.stereotype.Service;
import java.util.*;
/** Account view — reimplements COACTVWC: account + customer + cards. */
@Service public class AccountViewService {
    private final AccountRepository accounts; private final CardXrefRepository xrefs;
    private final CustomerRepository customers; private final CardRepository cards;
    public AccountViewService(AccountRepository a, CardXrefRepository x,
            CustomerRepository c, CardRepository cd){ this.accounts=a; this.xrefs=x; this.customers=c; this.cards=cd; }
    public Map<String,Object> view(Long acctId){
        Account acc = accounts.findById(acctId).orElseThrow(
            () -> new IllegalArgumentException("Account ID NOT found"));
        Map<String,Object> out = new LinkedHashMap<>();
        out.put("account", acc);
        xrefs.findByXrefAcctId(acctId).stream().findFirst().ifPresent(x -> {
            out.put("cards", cards==null?java.util.List.of():cards.findByCardAcctId(acctId));
            if (customers!=null) customers.findById(x.getXrefCustId()).ifPresent(c -> out.put("customer", c));
        });
        return out;
    }
}
