// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.service;

import com.carddemo.domain.*; import com.carddemo.repo.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.util.*;

/** Bill payment — reimplements COBIL00C PROCESS-ENTER-KEY. Pays the
 *  full current balance, records a payment transaction, zeroes the
 *  balance. Rejects when there is nothing to pay (balance <= 0). */
@Service public class BillPayService {
    private final AccountRepository accounts; private final TranRepository trans;
    private final CardXrefRepository xrefs;
    public BillPayService(AccountRepository a, TranRepository t, CardXrefRepository x){
        this.accounts=a; this.trans=t; this.xrefs=x; }
    @Transactional public Map<String,Object> pay(Long acctId){
        Account acc = accounts.findById(acctId).orElseThrow(
            () -> new IllegalArgumentException("Account ID NOT found"));
        BigDecimal balance = acc.getAcctCurrBal()==null?BigDecimal.ZERO:acc.getAcctCurrBal();
        if (balance.signum() <= 0) throw new IllegalStateException("You have nothing to pay...");
        BigDecimal payment = balance;            // COBIL00C pays the full balance
        acc.setAcctCurrBal(balance.subtract(payment));
        accounts.save(acc);
        String cardNum = xrefs.findByXrefAcctId(acctId).stream().findFirst()
            .map(CardXref::getXrefCardNum).orElse("");
        Tran t = new Tran();
        t.setTranId(BillPayService.nextTranId(trans));
        t.setTranTypeCd("02"); t.setTranCatCd(2L);
        t.setTranSource("POS TERM"); t.setTranDesc("BILL PAYMENT - ONLINE");
        t.setTranAmt(payment); t.setTranCardNum(cardNum); t.setTranMerchantId(0L);
        trans.save(t);
        return Map.of("acctId",acctId,"paymentAmount",payment,
            "newBalance",acc.getAcctCurrBal(),"tranId",t.getTranId());
    }
    static String nextTranId(TranRepository trans){
        String mx = trans.findTopByOrderByTranIdDesc().map(Tran::getTranId).orElse("0");
        long n; try { n = Long.parseLong(mx.trim()); } catch (Exception e) { n = 0L; }
        return String.format("%016d", n + 1);
    }
}
