// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.service;

import com.carddemo.domain.Card; import com.carddemo.repo.CardRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
/** Card update — reimplements COCRDUPC: update embossed name / expiry /
 *  CVV / status on an existing card (key card number is immutable). */
@Service public class CardUpdateService {
    private final CardRepository cards;
    public CardUpdateService(CardRepository c){ this.cards=c; }
    @Transactional public Card update(String cardNum, Card in){
        Card cur = cards.findById(cardNum).orElseThrow(
            () -> new IllegalArgumentException("Card NOT found"));
        if (in.getCardEmbossedName()!=null) cur.setCardEmbossedName(in.getCardEmbossedName());
        if (in.getCardExpiraionDate()!=null) cur.setCardExpiraionDate(in.getCardExpiraionDate());
        if (in.getCardCvvCd()!=null) cur.setCardCvvCd(in.getCardCvvCd());
        if (in.getCardActiveStatus()!=null) cur.setCardActiveStatus(in.getCardActiveStatus());
        return cards.save(cur);
    }
}
