// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.service;

import com.carddemo.domain.*; import com.carddemo.repo.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.util.*;
/** Daily transaction posting — reimplements CBTRN02C over the loaded
 *  DALYTRAN file: per record, resolve card->account via xref, apply the
 *  credit-limit guard (CYC-CREDIT - CYC-DEBIT + amt <= CREDIT-LIMIT),
 *  then post ACCT-CURR-BAL += amt with cycle credit/debit split by sign
 *  and the TCATBAL category running balance; overlimit/unknown rejected. */
@Service public class DailyPostingService {
    private final DalytranRepository daily; private final CardXrefRepository xrefs;
    private final AccountRepository accounts; private final TranRepository trans;
    private final TranCatBalRepository tcat;
    public DailyPostingService(DalytranRepository d, CardXrefRepository x,
            AccountRepository a, TranRepository t, TranCatBalRepository cb) {
        this.daily = d; this.xrefs = x; this.accounts = a; this.trans = t; this.tcat = cb; }
    private static BigDecimal nz(BigDecimal b) { return b == null ? BigDecimal.ZERO : b; }
    @Transactional public Map<String,Object> postDaily() {
        int posted = 0, rejected = 0;
        for (Dalytran d : daily.findAll()) {
            String card = d.getDalytranCardNum() == null ? "" : d.getDalytranCardNum().trim();
            CardXref x = xrefs.findById(card).orElse(null);
            if (x == null) { rejected++; continue; }
            Long acctId = x.getXrefAcctId();
            Account acc = accounts.findById(acctId).orElse(null);
            if (acc == null) { rejected++; continue; }
            BigDecimal amt = nz(d.getDalytranAmt());
            BigDecimal cr = nz(acc.getAcctCurrCycCredit());
            BigDecimal db = nz(acc.getAcctCurrCycDebit());
            BigDecimal limit = nz(acc.getAcctCreditLimit());
            if (limit.compareTo(cr.subtract(db).add(amt)) < 0) { rejected++; continue; }
            acc.setAcctCurrBal(nz(acc.getAcctCurrBal()).add(amt));
            if (amt.signum() >= 0) acc.setAcctCurrCycCredit(cr.add(amt));
            else acc.setAcctCurrCycDebit(db.add(amt));
            accounts.save(acc);
            String typeCd = d.getDalytranTypeCd(); Long catCd = d.getDalytranCatCd();
            if (typeCd != null && catCd != null) {
                TranCatBal cb = tcat.findByTrancatAcctIdAndTrancatTypeCdAndTrancatCd(acctId, typeCd, catCd)
                    .orElseGet(() -> { TranCatBal n = new TranCatBal();
                        n.setTrancatAcctId(acctId); n.setTrancatTypeCd(typeCd); n.setTrancatCd(catCd);
                        n.setTranCatBal(java.math.BigDecimal.ZERO); return n; });
                cb.setTranCatBal(nz(cb.getTranCatBal()).add(amt)); tcat.save(cb);
            }
            Tran t = new Tran(); t.setTranId(BillPayService.nextTranId(trans));
            t.setTranTypeCd(typeCd); t.setTranCatCd(catCd); t.setTranAmt(amt);
            t.setTranSource("POST"); t.setTranDesc("POSTED FROM DAILY FILE"); t.setTranCardNum(card);
            trans.save(t); posted++;
        }
        return Map.of("posted", posted, "rejected", rejected);
    }
}
