// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.service;

import com.carddemo.domain.*; import com.carddemo.repo.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.util.*;
/** Interest calculation — reimplements CBACT04C 1300-COMPUTE-INTEREST:
 *  monthlyInterest = (TRAN-CAT-BAL * DIS-INT-RATE) / 1200, accumulated per
 *  account; then ACCT-CURR-BAL += totalInterest, cycle credit/debit reset to
 *  0, and one interest Tran (type 01 / cat 5) written per category. */
@Service public class InterestService {
    private final AccountRepository accounts; private final TranRepository trans;
    private final TranCatBalRepository tcat; private final DisGroupRepository disc;
    private static final BigDecimal D1200 = new BigDecimal("1200");
    public InterestService(AccountRepository a, TranRepository t, TranCatBalRepository c, DisGroupRepository d){
        this.accounts=a; this.trans=t; this.tcat=c; this.disc=d; }
    @Transactional public Map<String,Object> runInterestCalc(){
        Map<Long,BigDecimal> perAcct = new LinkedHashMap<>();
        int written = 0;
        for (TranCatBal cb : tcat.findAll()) {
            Long acctId = cb.getTrancatAcctId(); if (acctId==null) continue;
            Account acc = accounts.findById(acctId).orElse(null); if (acc==null) continue;
            String groupId = acc.getAcctGroupId();
            BigDecimal rate = disc.findByDisAcctGroupIdAndDisTranTypeCdAndDisTranCatCd(
                groupId, cb.getTrancatTypeCd(), cb.getTrancatCd())
                .map(DisGroup::getDisIntRate).orElse(BigDecimal.ZERO);
            if (rate==null || rate.signum()==0) continue;
            BigDecimal catBal = cb.getTranCatBal()==null?BigDecimal.ZERO:cb.getTranCatBal();
            BigDecimal monthly = catBal.multiply(rate).divide(D1200, 2, RoundingMode.HALF_UP);
            if (monthly.signum()==0) continue;
            perAcct.merge(acctId, monthly, BigDecimal::add);
            Tran t = new Tran(); t.setTranId(BillPayService.nextTranId(trans));
            t.setTranTypeCd("01"); t.setTranCatCd(5L); t.setTranSource("System");
            t.setTranDesc("Int. for a/c " + acctId); t.setTranAmt(monthly);
            trans.save(t); written++;
        }
        for (Map.Entry<Long,BigDecimal> e : perAcct.entrySet()) {
            Account acc = accounts.findById(e.getKey()).orElse(null); if (acc==null) continue;
            acc.setAcctCurrBal((acc.getAcctCurrBal()==null?BigDecimal.ZERO:acc.getAcctCurrBal()).add(e.getValue()));
            acc.setAcctCurrCycCredit(BigDecimal.ZERO); acc.setAcctCurrCycDebit(BigDecimal.ZERO);
            accounts.save(acc);
        }
        return Map.of("accountsUpdated", perAcct.size(), "interestTxns", written);
    }
}
