// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.service;

import com.carddemo.domain.*; import com.carddemo.repo.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.util.*;
/** Transaction posting — reimplements CBTRN02C: credit-limit guard,
 *  then ACCT-CURR-BAL += amt with cycle credit/debit split by sign, and
 *  the TCATBAL category running balance. */
@Service public class PostingService {
    private final AccountRepository accounts; private final TranRepository trans;
    private final TranCatBalRepository tcatRepo;
    public PostingService(AccountRepository a, TranRepository t, TranCatBalRepository cb){
        this.accounts=a; this.trans=t; this.tcatRepo=cb; }
    @Transactional public Map<String,Object> post(Long acctId, String typeCd, Long catCd, BigDecimal amt){
        if (amt == null) throw new IllegalArgumentException("amount required");
        Account acc = accounts.findById(acctId).orElseThrow(
            () -> new IllegalArgumentException("ACCOUNT RECORD NOT FOUND"));
        BigDecimal cr = acc.getAcctCurrCycCredit()==null?BigDecimal.ZERO:acc.getAcctCurrCycCredit();
        BigDecimal db = acc.getAcctCurrCycDebit()==null?BigDecimal.ZERO:acc.getAcctCurrCycDebit();
        BigDecimal limit = acc.getAcctCreditLimit()==null?BigDecimal.ZERO:acc.getAcctCreditLimit();
        BigDecimal temp = cr.subtract(db).add(amt);     // CBTRN02C WS-TEMP-BAL
        if (limit.compareTo(temp) < 0) throw new IllegalStateException("OVERLIMIT TRANSACTION");
        acc.setAcctCurrBal((acc.getAcctCurrBal()==null?BigDecimal.ZERO:acc.getAcctCurrBal()).add(amt));
        if (amt.signum() >= 0) acc.setAcctCurrCycCredit(cr.add(amt));
        else acc.setAcctCurrCycDebit(db.add(amt));
        accounts.save(acc);
        if (tcatRepo != null && typeCd != null && catCd != null) {
            TranCatBal cb = tcatRepo.findByTrancatAcctIdAndTrancatTypeCdAndTrancatCd(acctId, typeCd, catCd)
                .orElseGet(() -> { TranCatBal n = new TranCatBal();
                    n.setTrancatAcctId(acctId); n.setTrancatTypeCd(typeCd); n.setTrancatCd(catCd);
                    n.setTranCatBal(BigDecimal.ZERO); return n; });
            cb.setTranCatBal((cb.getTranCatBal()==null?BigDecimal.ZERO:cb.getTranCatBal()).add(amt));
            tcatRepo.save(cb);
        }
        Tran t = new Tran(); t.setTranId(BillPayService.nextTranId(trans));
        t.setTranTypeCd(typeCd); t.setTranCatCd(catCd); t.setTranAmt(amt);
        t.setTranSource("POST"); t.setTranDesc("POSTED TRANSACTION");
        trans.save(t);
        return Map.of("acctId",acctId,"newBalance",acc.getAcctCurrBal(),"tranId",t.getTranId());
    }
}
