// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.service;

import com.carddemo.domain.Tran; import com.carddemo.repo.TranRepository;
import org.springframework.stereotype.Service;
import java.math.BigDecimal; import java.util.*;
/** Transaction report — reimplements CBTRN03C: total count and summed
 *  amount over the transaction file (the date-ranged detail the online
 *  CORPT00C report renders interactively). */
@Service public class ReportService {
    private final TranRepository trans;
    public ReportService(TranRepository t) { this.trans = t; }
    public Map<String,Object> transactionReport() {
        List<Tran> all = trans.findAll();
        BigDecimal total = BigDecimal.ZERO;
        for (Tran t : all) total = total.add(t.getTranAmt() == null ? BigDecimal.ZERO : t.getTranAmt());
        Map<String,Object> r = new LinkedHashMap<>();
        r.put("count", all.size()); r.put("totalAmount", total);
        return r;
    }
}
