// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.service;

import com.carddemo.domain.*; import com.carddemo.repo.*;
import org.springframework.stereotype.Service;
import java.util.*;
/** Statement generation — reimplements CBSTM03A: for each account join
 *  customer (via xref) + transactions and render a statement document. */
@Service public class StatementService {
    private final AccountRepository accounts; private final CardXrefRepository xrefs;
    private final CustomerRepository customers; private final TranRepository trans;
    public StatementService(AccountRepository a, CardXrefRepository x,
            CustomerRepository c, TranRepository t) {
        this.accounts = a; this.xrefs = x; this.customers = c; this.trans = t; }
    public List<String> generate() {
        List<String> statements = new ArrayList<>();
        for (Account acc : accounts.findAll()) {
            Long acctId = acc.getAcctId();
            StringBuilder sb = new StringBuilder();
            sb.append("STATEMENT FOR ACCOUNT ").append(acctId).append('\n');
            xrefs.findByXrefAcctId(acctId).stream().findFirst().ifPresent(x ->
                customers.findById(x.getXrefCustId()).ifPresent(c ->
                    sb.append("CUSTOMER: ").append(c.getCustFirstName()).append(' ')
                      .append(c.getCustLastName()).append('\n')));
            sb.append("CURRENT BALANCE: ").append(acc.getAcctCurrBal()).append('\n');
            statements.add(sb.toString());
        }
        return statements;
    }
}
