// [agentyx-provenance v1] generated by cobol_cics_to_springreact — do not edit; fix the emitter
package com.carddemo.service;

import com.carddemo.domain.Tran; import com.carddemo.repo.TranRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
/** Add transaction — reimplements COTRN02C ADD-TRANSACTION: validate
 *  required fields, generate TRAN-ID = max+1, persist. No balance post
 *  (manual entry; posting is PostingService/CBTRN02C). */
@Service public class TransactionService {
    private final TranRepository trans;
    public TransactionService(TranRepository t){ this.trans=t; }
    @Transactional public Tran add(Tran in){
        if (in.getTranAmt()==null) throw new IllegalArgumentException("Tran amount must be supplied");
        if (in.getTranTypeCd()==null || in.getTranTypeCd().isBlank())
            throw new IllegalArgumentException("Tran type CD must be supplied");
        in.setTranId(BillPayService.nextTranId(trans));
        return trans.save(in);
    }
}
